### ISSUE TITLE
A test run of transform-colors

### ISSUE THREAD

**Issue by dandaka** [brunchboy/afterglow#12]
I follow this guideline
https://github.com/brunchboy/afterglow/blob/master/doc/effects.adoc#layering-effects

I want to use transform-colors function to change colors in current show.

```
lights.my-show=> (color-fx/transform-colors (show/all-fixtures) :priority 1000)
(color-fx/transform-colors (show/all-fixtures) :priority 1000)
#afterglow.effects.Effect{:name "Transform Colors", :active-fn #object[afterglow.effects$always_active 0x3ba17151 "afterglow.effects$always_active@3ba17151"], :gen-fn #object[afterglow.effects.color$transform_colors$fn__16361 0x2d035551 "afterglow.effects.color$transform_colors$fn__16361@2d035551"], :end-fn #object[afterglow.effects$end_immediately 0x6d6ae297 "afterglow.effects$end_immediately@6d6ae297"]}
```

Nothing changes in the show. I have a guess, that this function can be used only with cue. Is that correct?

I guess this from following example:

```
(ct/set-cue! (:cue-grid *show*) 2 7
             (cues/cue :transform-colors (fn [_] (color-fx/transform-colors
                                                  (show/all-fixtures)))
                       :priority 1000))
```

Is there any way to test transform-colors without creating a cue?

**Comment by brunchboy** [comment]
`transform-colors` creates an effect (which you can see by the type of what it returns in your example above), so to do something this effect needs to be added to the running show, using `show/add-effect!`. Cues automatically create and add the effects they are configured with when they are activated, and end the effects when they are deactivated. In other words, cues are a way to conveniently create and control effects using MIDI controllers or the web UI. But you can manually create and add the effect from the REPL as well; that is the only step you were missing above. Try calling [show/add-effect!](http://deepsymmetry.org/afterglow/doc/afterglow.show.html#var-add-effect.21) with the results of calling `transform-colors`.

**Comment by brunchboy** [comment]
(And then, when you want to end that effect, call [show/end-effect!](http://deepsymmetry.org/afterglow/doc/afterglow.show.html#var-end-effect.21) using the same keyword you assigned the effect when you added it with `add-effect!`.)
