### ISSUE TITLE
Different color effect to different fixtures at the same time?

### ISSUE THREAD

**Issue by dandaka** [brunchboy/afterglow#24]
### What I want ##

I have a few groups of fixtures. I want to use different color effect on different fixtures.

### Code I have tried ##

1st try

```
    (show/add-effect! :color (afterglow.effects.color/color-effect
      "Plain red" (create-color "red") (show/fixtures-named "back-odd")))
    (show/add-effect! :color (afterglow.effects.color/color-effect
      "Plain Blue" (create-color "blue") (show/fixtures-named "back-even")))
```

2nd try

```
(defn separate-colors
  "Asign different colors to different fixtures. Experiment."
  []
  (afterglow.effects/scene "Different colors"
    (show/add-effect! :color (afterglow.effects.color/color-effect
      "Plain red" (create-color "red") (show/fixtures-named "back-odd")))
    (show/add-effect! :color (afterglow.effects.color/color-effect
      "Plain Blue" (create-color "blue") (show/fixtures-named "back-even")))
    )
  )
```

Result in both cases → only blue light, no red. Fixtures that supposed to be red are black. 

What is the proper way to assign different effect to different fixtures?

**Comment by brunchboy** [comment]
Either of those will work but for one issue: you are assigning both of the effects the same key. A key is used to uniquely identify a running effect, so you can replace it later. So the blue `:color` effect is replacing the red `:color` effect. If you instead call them, e.g. `:odd-color` and `:even-color` they will be able to coexist. Then you will need to end them individually by using the appropriate keys later.

**Comment by brunchboy** [comment]
Or perhaps `:back-odd-color` and `:back-even-color` because it looks like you are going to have other effects that are not in the back… but hopefully this gives the idea, anyway.

**Comment by dandaka** [comment]
1) Is there a way to end effect simply when moving out to another scene/cue? I see only solution to always shut down effects like this on each scene/cue `(show/end-effect! :unique-key)`, which is not a nice workaround.

2) If a key is designed to uniquely identify a effect, maybe it is possible to assign different colors to different fixtures in one effect?

**Comment by brunchboy** [comment]
I don’t understand the first question. If the effect is created by a cue, the cue will end the effect when the cue ends.

As for the second question, your effect can certainly assign different colors to different fixtures; my rainbow chase examples do that, using spatial parameters, for example. But you can also use a scene to combine multiple different single-color effects which are working with different fixtures, and have the cue control the entire scene. The scene will have its own key, separate from its component effects.

**Comment by dandaka** [comment]
I am trying it here #26 with little result, looks like a bug.
