### ISSUE TITLE
Scene with different colors on different fixtures fails

### ISSUE THREAD

**Issue by dandaka** [brunchboy/afterglow#26]
I create a new cue

```
  (ct/set-cue! (:cue-grid *show*) 0 17
    (cues/cue :color  (fn [_] (afterglow.effects/scene
      "Blue and red"
        (show/add-effect! :color-back-odd (afterglow.effects.color/color-effect
          "Plain red" (create-color "red") (show/fixtures-named "back-odd")))
        (show/add-effect! :color-back-even (afterglow.effects.color/color-effect
          "Plain Blue" (create-color "blue") (show/fixtures-named "back-even")))
    ))))
```

This code in context https://github.com/dandaka/lights-experiment/blob/master/src/lights/my_show.clj#L428

When I click on this cue in web interface, Afterglow start to send lots of errors:

Log: https://gist.github.com/dandaka/adba9374fc8ca2541063

This code is working:

```
(afterglow.effects/scene
      "Blue and red"
        (show/add-effect! :color-back-odd (afterglow.effects.color/color-effect
          "Plain red" (create-color "red") (show/fixtures-named "back-odd")))
        (show/add-effect! :color-back-even (afterglow.effects.color/color-effect
          "Plain Blue" (create-color "blue") (show/fixtures-named "back-even")))
    )
```

**Comment by brunchboy** [comment]
In neither case should you call `show/add-effect` within the scene. The scene combines the inner effects into a single combined effect and returns that. The outer code will take care of adding the effect.

**Comment by dandaka** [comment]
Thank you, I've added this as an example too.

**Comment by brunchboy** [comment]
You did that so quickly that you must have figured it out yourself while I was in a meeting? Thanks, I will test those and merge them after work.

**Comment by dandaka** [comment]
No, it was your tip. Maybe I was using scenes wrong? I think I have found example somewhere...

Now I have tried this:

```
(show/add-effect! :color (afterglow.effects/scene "Different colors"
  (afterglow.effects.color/color-effect
    "Plain red" (create-color "red") (show/fixtures-named "odd"))
  (afterglow.effects.color/color-effect
    "Plain Blue" (create-color "blue") (show/fixtures-named "even"))
  ))
```

And it worked also. Since it works also with cues, it makes sense to use this as an example.

**Comment by brunchboy** [comment]
By the way, this discussion has reminded me that I want to create some effects that automate the process of dividing your fixtures into alternating groups, based on their location along some axis, and then let you assign a different color parameter to each group. I think I will try that tonight, and add them as examples. I want to show two different ways of doing it, one by actually grouping the fixtures, and one by using a spatial param that creates an alternating color pattern in space, which you can send to all the fixtures (and then by using an oscillator, shift where the color bands are in time with the music).
