### ISSUE TITLE
Way to debug Dynamic parameter?

### ISSUE THREAD

**Issue by dandaka** [brunchboy/afterglow#31]
Can't find any way to see evaluate value of a Dynamic parameter. Is there any?

**Comment by brunchboy** [comment]
You have the full power of Clojure at your disposal, so there are lots of ways to probe the parameter. I am not sure what you mean here, though. Remember that a dynamic parameter’s value depends on the show context, metronome snapshot, and possibly a fixture head. To ask it what its value is in that context, you call:

```clojure
(afterglow.effects.params/evaluate param show snapshot head)
```

That is exactly how Afterglow does it.

Here is the API documentation of the [IParam](http://deepsymmetry.org/afterglow/doc/afterglow.effects.params.html#var-IParam) protocol which all dynamic parameters implement.

**Comment by brunchboy** [comment]
Also I just realized you may be asking a simpler question of how to look in a show variable. You can just call `(show/get-variable :beat-ratio)` for example. Typing on my phone so I did not double-check the API but I think that is correct.

**Comment by dandaka** [comment]
Latest works, thank you! Plz don't close, so I could update docs later.

**Comment by brunchboy** [comment]
Sure. And even after the issues are closed, they will be searchable, I expect it will be useful to point people at them from time to time.

Also, I just remembered that you can also tell Afterglow to call a function (which can do whatever you want) whenever a particular show variable changes. When debugging, you could add one that, for example, prints out the new value, or uses timbre to log it. The way you set that up is [show/add-variable-set-fn!](http://deepsymmetry.org/afterglow/doc/afterglow.show.html#var-add-variable-set-fn.21)
