### ISSUE TITLE
Dynamic parameter linked to another parameter with a function?

### ISSUE THREAD

**Issue by dandaka** [brunchboy/afterglow#32]
I want to:
1. Bind MIDI mapping (0...127) to a parameter A (1...4)
2. Have another parameter, that has fn(A)=A² (for example)

This looks promising
https://github.com/brunchboy/afterglow/blob/master/doc/parameters.adoc#variable-parameters

But example doesn't make any sense now. And without debug (#31) its hard to experiment.

My end goal is to control beat-ration with MIDI, which is working well with existing dynamic parameters. I need to have some fn to round() and square it.

**Comment by brunchboy** [comment]
You can call `taoensso.timbre/info` to log at the `:info` level even when debugging is suppressed.

I am not positive exactly what you are trying to achieve here; you can write your own dynamic parameters which use any functions that you like, but you may also want to write your own oscillator instead. If you can precisely describe what you are trying to accomplish, i.e what is the input, what is the desired output, I could give you some potential implementations.

If nothing else, I can imagine writing an alternate version of variable-parameter which takes an arbitrary mathematical function and applies it to the value it finds in the show variable. That would be quite easy. Actually, we could add such a function as an optional keyword argument to the existing variable parameter implementation. Would that do everything you need?

**Comment by dandaka** [comment]
Hm, let me try once again.

I have MIDI input that is linked to a Dynamic parameter:

```
(show/add-midi-control-to-var-mapping
        "Automap MIDI" 10 22 :beat-ratio :min 1 :max 4)
```

AFAIK, it gives linear approximation, so I have 1,2,3,4 values inside :beat-ratio.

What I try to achive is to get 1,2,4,8,16.

So my guess is I need to use some function, say (in JavaScript)

beat-ratio-sq = 2 ^ beat-ratio

It is not clear from a current state of documentation, how to achieve that.

**Comment by brunchboy** [comment]
Currently you would need to write your own dynamic parameter implementation to do that. Later tonight I may be able to add an option to `build-variable-parameter` so you could, for example:

```clojure
(params/build-variable-param :beat-ratio :transform (fn [v] Math/pow 2 v))
```

In other words, I could add a `:transform` optional keyword argument to the function, which you pass an arbitrary Clojure function which gets applied to the value found in the show variable before returning it as the value of the parameter. That example would raise 2 to the power of whatever is found in the show variable named `:beat-ratio`, which is where your MIDI mapping is storing its numbers.

**Comment by dandaka** [comment]
That would be a cool feature to have!

**Comment by dandaka** [comment]
Another use case for this — change from linear bindings to exponential. For example, "chance" in Sparkle effect is much better to control with exponential function.

**Comment by brunchboy** [comment]
I agree to both comments! And it should be pretty easy too. I will try to find time tonight.

**Comment by brunchboy** [comment]
An alternative place to add the `:transform` function would be in `show/add-midi-control-to-var-mapping` so the variable would just get set the way you want based on incoming MIDI in the first place. I think both should be implemented. In both cases you will need to be careful the function is fast so it doesn't mess up MIDI delivery or frame rendering.

**Comment by brunchboy** [comment]
All right, I have implemented it on the MIDI mapping function first. You can now do this (in the latest 0.1.6-SNAPSHOT release):

```clojure
(show/add-midi-control-to-var-mapping
  "Automap MIDI" 10 22 :beat-ratio :max 3
  :transform-fn (fn [v] (Math/pow 2 (Math/round v))))
```

First it scales the MIDI control value to the range 0-3 (rather than 1-4 as you were doing, because that makes the rest of the math simpler), then calls a custom transformation function which rounds the scaled value to the nearest integer, then raises 2 to that power. The result of that custom function is 1, 2, 4, or 8, depending on where the MIDI control is set. The result gets put in `:beat-ratio`.

**Comment by dandaka** [comment]
Works great! Thank you :+1:
