### ISSUE TITLE
Running code in a cue?

### ISSUE THREAD

**Issue by dandaka** [brunchboy/afterglow#34]
I want to reset a show metronome, when cue is pressed. I follow your examples from #30 

```
  (ct/set-cue! (:cue-grid *show*) 7 7
    (cues/cue :set-main-hue
      (fn [_] (afterglow.effects.scene
        "Reset beat"
        (afterglow.rhythm/metro-start (:metronome *show*) 1)))
        :held true))
```

Another try:

```
(ct/set-cue! (:cue-grid *show*) 7 7
             (cues/cue :set-main-hue
                       (fn [_] (reset-beat))))
```

No luck. I got, that cues and scenes are working with effects. What to do in cases, when code is not an effect?

**Comment by brunchboy** [comment]
You do need to return an effect from the cue‘s effect-creation function. Creating a blank effect as the last statement in the function will return it. In other words, this may work:

```clojure
(ct/set-cue! (:cue-grid *show*) 7 7
    (cues/cue :set-main-hue
      (fn [_] (afterglow.rhythm/metro-start (:metronome *show*) 1)
              (afterglow.effects/blank))
        :held true))
```

Also there was another issue with your first attempt: `afterglow.effects.scene` should have been `afterglow.effects/scene`.

In the long run, I think it would be good to add a special kind of degenerate cue creation function to make this kind of use case even easier.

**Comment by brunchboy** [comment]
Whoops, this won’t work because the effect creation function gets called before the cue is actually launched, to validate that it returns an effect. So We need to move the running of the code into an actual dummy effect, which will run it when the effect is started. I am working on that.

**Comment by brunchboy** [comment]
OK, if you update your Afterglow snapshot, I have added a way to do this easily. It was a little tricky to get all the details right, because I wanted both a good user experience, and efficient implementation, so I needed to create both a new kind of degenerate effect to support this, and a new cue-creation function to build that easily. I have added [documentation](https://github.com/brunchboy/afterglow/blob/master/doc/cues.adoc#creating-code-cues), and tested that you can achieve your specific use case like this:

```clojure
(ct/set-cue! (:cue-grid *show*) 7 7
             (cues/code-cue (fn [show snapshot]
                              (rhythm/metro-start (:metronome show) 1))
                            "Reset"))
```

**Comment by dandaka** [comment]
Works, thank you! Anyway my old code was also working and saved my sync, because Traktor BPM sync wasn't working that time.

**Comment by brunchboy** [comment]
Yes, your old code works, just more often than it should; whenever that cue is created, it resets the metronome, not just when it is activated. So reloading the file or function could unexpectedly reset the metronome.

Another thing you might want to consider: Set up one of your MIDI controller buttons as a tap tempo button that you can fall back on when automatic sync is not working. There are a number of functions in `show.clj` for that, starting with [add-midi-control-metronome-align-bar-mapping](http://deepsymmetry.org/afterglow/doc/afterglow.show.html#var-add-midi-control-metronome-align-bar-mapping). Oh, there was already one you could have been using for [resetting the metronome](http://deepsymmetry.org/afterglow/doc/afterglow.show.html#var-add-midi-control-metronome-reset-mapping), as long as you had a button that was available and not part of a cue grid.
