### ISSUE TITLE
Traktor sync explanation needed

### ISSUE THREAD

**Issue by dandaka** [brunchboy/afterglow#37]
```
Whenever Afterglow detects a coordinated stream of messages on controllers 0 through 4 which are consistent with beat-phase information from this Traktor mapping, it offers that MIDI input device as a source of Traktor beat-phase synchronization, and if it is synchronizing a metronome with the MIDI clock messages on that port, will also synchronize the beats.
```

I am trying:

```
(afterglow.midi/sync-to-midi-clock)
(afterglow.midi/sync-to-midi-clock)

IllegalArgumentException No MIDI clock sources were found.  afterglow.midi/sync-to-midi-clock (midi.clj:551)
```

Also webinterface doesn't show anything. When I start clock send from Traktor, I can sync via clock. But without beat phase correction.

**Comment by brunchboy** [comment]
Did you install and configure my Traktor mapping file?

**Comment by dandaka** [comment]
I have installed it. Should it be configured somehow?

**Comment by dandaka** [comment]
Also I've tried
`(show/sync-to-external-clock (afterglow.midi/sync-to-midi-clock))`

**Comment by brunchboy** [comment]
Yes, it does need to be configured as described in the Traktor documentation. I believe I linked to it in my documentation. Checking now…

In [Syncing to MIDI Clock](https://github.com/brunchboy/afterglow/blob/master/doc/mapping_sync.adoc#syncing-to-midi-clock) I have a tip that links to the Traktor Knowledge Base [article](http://www.native-instruments.com/en/support/knowledge-base/show/750/how-to-send-a-midi-clock-sync-signal-in-traktor/) about how to configure Traktor to send clock messages. That needs to be done first, then my TSI can add the beat phase information. I will add a note to make that more clear.

**Comment by brunchboy** [comment]
All right, I expanded the warning in [Syncing to Traktor Beat Phase](https://github.com/brunchboy/afterglow/blob/master/doc/mapping_sync.adoc#syncing-to-traktor-beat-phase) to emphasize that you still need to configure Traktor to send the MIDI data on the correct port, and to send MIDI clock messages.

**Comment by dandaka** [comment]
Works, thank you!
