### ISSUE TITLE
Java MIDI limitation

### ISSUE THREAD

**Issue by dandaka** [brunchboy/afterglow#38]
Just wanted to share some thoughts about this:

> If this happens, remember that you need to have all of your MIDI devices hooked up before you start Afterglow, because of limitations in the Java MIDI implementation. Try quitting and restarting Afterglow. If that doesn’t help, you will need to troubleshoot your MIDI setup.

In live performance mode one of my devices (shitty Novation Nocturn, which every sane person should avoid) got "disconnected" from my laptop. Reconnecting the device didn't solved the problem, since Java doesn't seem to care to hotlinking devices. I have tough choice between restarting Afterglow (and lose the show for like 5 seconds) or lose MIDI control. Latest was more important, so I restarted.

But you can see, that this could pretty bad issue with big shows, that have no such option as losing all the lights.

I think I could workaround this by creating a Max patch, which will be always "connected". But solving one issue by bringing more components into a play is a pretty shit solution, IMO. More components → bigger chance of failure.

**Comment by brunchboy** [comment]
I hate this, but it is something that has to be solved outside of Afterglow. Derek Cook is close to releasing his version of a minimal CoreMIDI to Java SPI that we have been talking about. It still doesn’t support hot-plugging, but since it will be open source, he and I (and perhaps even you) could work on that part next.

**Comment by dandaka** [comment]
That is good news. I wish I could be any help, but my programming skill is pretty basic at this time.

**Comment by brunchboy** [comment]
That’s fine! Your input and ideas have been great help in other areas. And I will pass this along to Derek, he was feeling a bit discouraged last week, but having a real person who would benefit from the work is always a good motivator. :grinning:

**Comment by dandaka** [comment]
You can definitely tell Derek (with big hi from Russia), that this issue is a huge pain, that could break completely some scenarios like one outlined above. I can "close my eyes" on this, since level is not that high. But for big production this is a changer.

**Comment by brunchboy** [comment]
Some great news on this front. I stayed up far too late last night tinkering with Derek’s code and researching how we can properly detect environment changes. Right after I gave up and was writing a StackOverflow question, I discovered the final missing piece, and sent him an approach that should work. He tested it while I was sleeping (I believe he is in the UK) and confirmed that it works. So once he has some time to fix up the details, we will have a solution to let Afterglow work with MIDI devices whenever they are connected.

**Comment by brunchboy** [comment]
CoreMIDI4J is still progressing nicely. I found and fixed some issues when multiple MIDI messages arrive at the same time (which happens with my Traktor beat phase mapping), and Derek is close to having the environment change detection working. Afterglow has already been modified to prefer CoreMIDI4J as its MIDI Service Provider Interface when it is installed, and I hope soon to have a release that I can point you at, with instructions on how to install it.

I have been working more on that then Afterglow for the past few days, because it is such an important and long-standing problem with MIDI in Java on the Mac.

**Comment by brunchboy** [comment]
Derek and I have continued to make good progress on [CoreMIDI4J](https://github.com/DerekCook/CoreMidi4J). He’s traveling for work right now, but at the end of the week, he should be able to integrate my last round of improvements, and release the version that I am going to target Afterglow to use. I am now working on adding support within Afterglow for changes to the MIDI environment, including a way to have it watch for a particular device to be connected, and when it is, set up the mappings that you want that device to use. That will mean that in a performance environment, if your controller drops out, as soon as it comes back, your mappings will be reconfigured.

I would like to close all the other issues that I feel I have addressed, and prepare for a new release of Afterglow. I had been waiting for you to confirm whether my changes were helpful, but it seems you’ve become busy with other projects?

**Comment by dandaka** [comment]
Yep, a newborn daughter is my new project :) Need some time to set everything up. Anyway next gig is coming in February, so I'll get back soon.

**Comment by brunchboy** [comment]
Congratulations! That does tend to pre-empt other projects. :grin:

**Comment by brunchboy** [comment]
Excellent! I have environment-change handling working exactly how I want now. I can tell Afterglow I want to use my Ableton Push with a show, and as soon as it is plugged in or powered on, Afterglow lights it up and starts using it; if I power it down or unplug it, Afterglow stops trying to use it until it reappears again.

It still relies on an unreleased version of CoreMIDI4J, but Derek is back from his business trip, and plans to merge my fixes tomorrow night and cut another release, so soon you will be able to do this sort of thing as well.

**Comment by dandaka** [comment]
Can't wait to test!

**Comment by brunchboy** [comment]
All right, this is ready for you to try!

First you will want to install the most recent release of [CoreMIDI4J](https://github.com/DerekCook/CoreMidi4J/releases).

Then update to the latest Afterglow snapshot with `lein -U deps`, and read these [instructions](https://github.com/brunchboy/afterglow/blob/master/doc/mapping_sync.adoc#automatically-creating-bindings-when-a-device-connects) for how to set up Afterglow to automatically run your binding commands when a particular device is connected.

Then verify that your mappings are set up, unplug your device, plug it back in, wait a second, and see if the mappings work again. Please let me know how this works for you. It has been a huge improvement for me, which I have long wanted to achieve.

This release is getting huge! I am going through the rest of the documentation now to see what else needs to change. Then I’ll do a little more cleanup and improvement of the MIDI code (I am a much better Clojure programmer today than when I first wrote it), and hopefully release 0.1.6 tomorrow.

**Comment by dandaka** [comment]
#49 blocks

**Comment by dandaka** [comment]
Works fine for me! Thank you!

**Comment by brunchboy** [comment]
Great! It is looking like time to release Afterglow 0.1.6 soon. (You will probably want to move to 0.1.7-SNAPSHOT at that point in order to keep up with things as I write them. I will let you know when that becomes available.)
