### ISSUE TITLE
How to run local Afterglow against local version of it?

### ISSUE THREAD

**Issue by dandaka** [brunchboy/afterglow#40]
I want to make some changes to Web UI of Afterglow. I can't find Afterglow in my project folder (as was expected from Node/Bower experience). Do I need to use Clojars for it?

I have found sources, but could not find way to launch them.

**Comment by brunchboy** [comment]
When you run Afterglow as a library, it stays compressed in a jar file inside your own project. Even if you do that, though, good Clojure environments like Cider and Cursive will let you dive into the source of functions you are calling, and redefine them on the fly. For web UI stuff which is not Clojure, however, that would be more difficult. So you can tell Leiningen to use your local checkout of Afterglow instead, as described in the [checkout dependencies](https://github.com/technomancy/leiningen/blob/stable/doc/TUTORIAL.md#checkout-dependencies) section of the Leiningen tutorial.

Or you can just run Afterglow from its own checkout, and experiment there. That is how I normally run Afterglow. You just need to clone the repo, and then you can run `lein repl` in the top-level directory (or `cider-jack-in` from Emacs, or however you tell Cursive to start a REPL if you are using that IDE).

You can do a combination of these things too; running Afterglow from its own repo when you are mostly hacking on it, running it as a checkout dependency of your own project when you are hacking on both, and switching back to a downloaded dependency by removing the checkout link when you want to go back to a more standard library use.

**Comment by brunchboy** [comment]
By the way, this is the kind of question that the [Clojure Google Group](https://groups.google.com/forum/#!forum/clojure) can be very helpful with.
