### ISSUE TITLE
Scenes and chases deserve their own heading

### ISSUE THREAD

**Issue by dandaka** [brunchboy/afterglow#44]
I was looking for scenes/chases and could not find documentation, until I found this:

http://take.ms/Pxwv3

I think they are so important, that deserve at least their own H2 heading (maybe even a page).

If you wish, I could make a pull request with little restructure.

**Comment by brunchboy** [comment]
I agree, they should be more prominent. We can either just leave this issue open to remind me to do that, or you can submit a PR.

**Comment by brunchboy** [comment]
All right, they are in the table of contents and described in the overview now. Long overdue, thanks!
