### ISSUE TITLE
Can't get a conditional effect working inside a cue

### ISSUE THREAD

**Issue by dandaka** [brunchboy/afterglow#47]
### End goal ###

To control dimmers from Live by sending MIDI notes/CCs.

### I have ###

`:front-1-note` oscillates between digits 0 and 1 (MIDI note). I add a cue with code:
https://github.com/dandaka/lights-experiment/blob/master/src/lights/my_show.clj#L458-L467

Web interface has this button. All other cues in this row are working correctly. This button deselects whole row.

This also not working:

```
(show/add-effect! :condition (afterglow.effects/conditional-effect "Enabled?" (params/build-variable-param :front-1-note)
          (dimmer-effect 255 (show/fixtures-named "front") :add-virtual-dimmers? true :htp? false)
        ))
```

What do I miss?

### Guesses ###

1. Something is wrong with `afterglow.effects/conditional-effect` syntax
2. Something is wrong with `(params/build-variable-param :front-1-note)`

**Comment by dandaka** [comment]
I think I've found the reason. Scene can't have only 1 effect? Why is that?

**Comment by dandaka** [comment]
Found all the solutions :)

**Comment by brunchboy** [comment]
I’m glad you were able to figure this out while I slept! :wink:
