### ISSUE TITLE
Olad not working not shown in REPL

### ISSUE THREAD

**Issue by dandaka** [brunchboy/afterglow#48]
I use `(core/init-logging)` to start logging. When I forget to launch olad, I don't get any errors (except web interface). Don't you think it should be included in REPL output? Since its an essential component of Afterglow.

**Comment by brunchboy** [comment]
There isn’t necessarily a REPL (Afterglow might be running in the background as an executable jar, or inside Max/MSP), so the errors go to the places that are sure to exist: the log files (which are echoed to the Max/MSP console window), and the user interface.

The only way I could be sure to have you see something in the REPL would be to throw an exception and fail to start, and Afterglow is designed to be more graceful than that. The show is failing to send DMX, and logging errors, but as soon as you start olad, and plug in your DMX interface, Afterglow recovers and starts working.

**Comment by brunchboy** [comment]
When I am working on stuff that is liable to break, I tend to be in the habit of keeping a terminal window open running `tail -f logs/Afterglow.log`. :grin:

**Comment by brunchboy** [comment]
Similarly, if you kill olad or unplug your DMX interface in the middle of a show, you will get into that same error state. But again if you restart olad and plug in the interface, Afterglow recovers.

**Comment by dandaka** [comment]
Thank you for the tip!
