### ISSUE TITLE
Cue MIDI mappings stopped working

### ISSUE THREAD

**Issue by dandaka** [brunchboy/afterglow#49]
```
nREPL server started on port 62114 on host 127.0.0.1 - nrepl://127.0.0.1:62114
REPL-y 0.3.7, nREPL 0.2.10
Clojure 1.8.0-RC4
Java HotSpot(TM) 64-Bit Server VM 1.6.0_65-b14-468-11M4833
my-show loaded.
lights.my-show=> (cues/add-midi-control-to-cue-mapping "quneo" 0 :note 36 0 7)
(cues/add-midi-control-to-cue-mapping "quneo" 0 :note 36 0 7)

ClassNotFoundException javax.sound.midi.MidiDeviceReceiver  java.net.URLClassLoader$1.run (URLClassLoader.java:202)
lights.my-show=> (cues/add-midi-control-to-cue-mapping "quneo" 0 :note 36 0 7)
(cues/add-midi-control-to-cue-mapping "quneo" 0 :note 36 0 7)

NoClassDefFoundError uk/co/xfactorylibrarians/coremidi4j/CoreMidiReceiver  uk.co.xfactorylibrarians.coremidi4j.CoreMidiDestination.getReceiver (CoreMidiDestination.java:173)
```

Also please note, that same command gives two different errors.

**Comment by brunchboy** [comment]
Did you place both the .jar file and the .dylib files in /Library/Java/Extensions? Could you move this to the [CoreMIDI4J](https://github.com/DerekCook/CoreMidi4J/issues) project so Derek can help? He is in a closer time zone to you as well.

**Comment by brunchboy** [comment]
Also, what (if any) other files do you have in /Library/Java/Extensions?

**Comment by brunchboy** [comment]
Oh! I think I see the problem. You seem to be using Java 1.6, but CoreMIDI4J requires at least Java 1.7. Is there a reason you cannot use a more recent release of Java?

**Comment by brunchboy** [comment]
In the mean time, if you cannot (or are not ready to) install a current release of Java, you can restore your ability to use Afterglow and other Java MIDI applications by removing the CoreMIDI4J files from /Library/Java/Extensions.

**Comment by dandaka** [comment]
Java 1.8, ok. Do I need JDK or JRE? This Java is always make me cry bloody tears :)

**Comment by dandaka** [comment]
Also, do you think its good idea to tell author of CoreMIDI4J to include Java version error in logs?

**Comment by brunchboy** [comment]
I think you only need the JRE; the JDK gives you the Java compiler as well. I don’t believe Clojure needs the JDK, but I will double check.

And I do think that suggestion about CoreMIDI4J is a good idea. An even better idea would be to fail gracefully, and simply do nothing, if it is in an environment where it cannot work. I had already suggested doing that for cases where the .dylib file is missing, and we can now suggest to try to make the same thing happen if the Java version is too old.

**Comment by brunchboy** [comment]
Indeed, you only need the JRE for Clojure, as reported [here](http://stackoverflow.com/questions/4807460/does-clojure-require-a-jdk). And I have passed on your suggestion to Derek.

**Comment by brunchboy** [comment]
But, hmm, Leiningen seems to want a JDK: https://github.com/technomancy/leiningen#installation

So that might be the safest bet. I don’t think it is much larger. As a developer, I always install the JDK anyway.

**Comment by dandaka** [comment]
Now works fine! Thank you.

**Comment by brunchboy** [comment]
That’s excellent news! Now I hope that you can get device reconnection and auto-binding working!

**Comment by dandaka** [comment]
Device reconnection and auto-binding works, thank you!

**Comment by brunchboy** [comment]
Wonderful. I got side-tracked on another CoreMIDI4J issue yesterday, and so decided to hold off on releasing Afterglow 1.6 until you had a chance to test some of these enhancements. This is a good start.
